import android.content.SharedPreferences

object Loc {
    val availableLanguages = listOf(

        Triple("ar", "Arabic", "العربية"),
        Triple("en", "English", "English"),
        Triple("bn", "Bengali", "বাংলা"),
        Triple("zh", "Chinese", "中文"),
        Triple("cs", "Czech", "Čeština"),
        Triple("da", "Danish", "Dansk"),
        Triple("nl", "Dutch", "Nederlands"),
        Triple("fi", "Finnish", "Suomi"),
        Triple("fr", "French", "Français"),
        Triple("de", "German", "Deutsch"),
        Triple("el", "Greek", "Ελληνικά"),
        Triple("hi", "Hindi", "हिन्दी"),
        Triple("id", "Indonesian", "Bahasa Indonesia"),
        Triple("it", "Italian", "Italiano"),
        Triple("ja", "Japanese", "日本語"),
        Triple("ko", "Korean", "한국어"),
        Triple("ku", "Kurdish (Sorani)", "کوردی (سۆرانی)"),
        Triple("no", "Norwegian", "Norsk"),
        Triple("ps", "Pashto", "پښتو"),
        Triple("fa", "Persian", "فارسی"),
        Triple("pl", "Polish", "Polski"),
        Triple("pt", "Portuguese (Brazil)", "Português (Brasil)"),
        Triple("ro", "Romanian", "Română"),
        Triple("ru", "Russian", "Русский"),
        Triple("es", "Spanish", "Español"),
        Triple("sv", "Swedish", "Svenska"),
        Triple("tr", "Turkish", "Türkçe"),
        Triple("uk", "Ukrainian", "Українська"),
        Triple("ur", "Urdu", "اُردُو")
    )

    private val translations = mapOf(
        "ar" to mapOf(
            "lang_title" to "Language / اللغة",
            "home_section" to "تخصيص الصفحة الرئيسية",
            "trending" to "الرئيسية (Trending)",
            "manage_channels" to "إدارة القنوات والقوائم",
            "manage_channels_sum" to "إضافة، تعديل، أو إعادة ترتيب قنواتك",
            "account_section" to "إعدادات الحساب والكوكيز",
            "login_btn" to "تسجيل الدخول / تحديث الكوكيز",
            "login_sum" to "سجّل دخولك بحساب جوجل ليتم التقاط كوكيز الجلسة",
            "status_title" to "حالة الحساب",
            "status_logged_in" to "تم تسجيل الدخول (الكوكيز موجودة)",
            "status_logged_out" to "غير مسجل (وضع التصفح الخفي)",
            "visitor_id" to "معرّفك للصفحة الرئيسية",
            "edit_manual" to "تعديل يدوياً",
            "logout_btn" to "تسجيل الخروج (حذف الكوكيز)",
            "logout_confirm_title" to "تأكيد تسجيل الخروج",
            "logout_confirm_msg" to "هل أنت متأكد أنك تريد تسجيل الخروج ومسح جميع الكوكيز؟",
            "browsing_section" to "تخصيص التصفح والبحث",
            "player_engine" to "محرك التشغيل",
            "player_advanced" to "متقدم (1080p/4K + ترجمة تلقائية)",
            "player_classic" to "كلاسيكي (مدمج CloudStream)",
            "pages_limit" to "عدد صفحات تحميل القناة",
            "pages_sum" to "عدد الصفحات التي يتم جلبها عند فتح قناة",
            "playlist_tag" to "وسم بحث القوائم",
            "tag_hint" to "اكتب الوسم الذي تريده (مثال: {p})",
            "current" to "الحالي: ",
            "saved_msg" to "تم حفظ بيانات تسجيل الدخول بنجاح",
            "cleared_msg" to "تم حذف البيانات",
            "close" to "إغلاق",
            "save" to "حفظ",
            "ok" to "حسناً",
            "cancel" to "إلغاء",
            "delete" to "حذف",
            "youtube_login" to "تسجيل دخول يوتيوب",
            "no_data" to "لم يتم العثور على بيانات",
            "add_channel_btn" to "+ إضافة قناة أو قائمة",
            "no_channels" to "لم يتم إضافة أي قنوات بعد.",
            "unnamed_section" to "قسم بدون اسم",
            "confirm_delete_title" to "تأكيد الحذف",
            "confirm_delete_msg" to "سوف يتم إزالة هذه القناة من الصفحة الرئيسية نهائياً.",
            "section_name" to "اسم القسم",
            "add_new" to "إضافة جديد",
            "edit_item" to "تعديل",
            "url_empty" to "الرابط لا يمكن أن يكون فارغاً",
            "browse_youtube" to "تصفح ليتعرف يوتيوب على تفضيلاتك",
            "url_hint" to "الرابط (https://...)"
        ),
        "en" to mapOf(
            "lang_title" to "Language / اللغة",
            "home_section" to "Change homepage sections",
            "trending" to "Trending",
            "manage_channels" to "Manage Homepage Channels",
            "manage_channels_sum" to "Add, edit, or reorder custom channels and playlists",
            "account_section" to "Account & Cookies",
            "login_btn" to "Login / Update Cookies",
            "login_sum" to "Sign in with Google to capture session cookies",
            "status_title" to "Account Status",
            "status_logged_in" to "Logged In (Cookies Active)",
            "status_logged_out" to "Not Logged In (Incognito)",
            "visitor_id" to "Visitor ID",
            "edit_manual" to "Edit Manually",
            "logout_btn" to "Logout (Clear Cookies)",
            "logout_confirm_title" to "Confirm Logout",
            "logout_confirm_msg" to "Are you sure you want to log out and clear all cookies?",
            "browsing_section" to "Browsing & Search",
            "player_engine" to "Player Engine",
            "player_advanced" to "Advanced (1080p/4K + Auto-Translate)",
            "player_classic" to "Classic (CloudStream Built-in)",
            "pages_limit" to "Channel Pages Limit",
            "pages_sum" to "Pages fetched when opening a channel",
            "playlist_tag" to "Playlist Search Tag",
            "tag_hint" to "Enter tag (e.g. {p} or playlist:)",
            "current" to "Current: ",
            "saved_msg" to "Login data saved successfully",
            "cleared_msg" to "Data cleared",
            "close" to "Close",
            "save" to "Save",
            "ok" to "OK",
            "cancel" to "Cancel",
            "delete" to "Delete",
            "youtube_login" to "YouTube Login",
            "no_data" to "No data found!",
            "add_channel_btn" to "+ Add Channel / Playlist",
            "no_channels" to "No channels added yet.",
            "unnamed_section" to "Unnamed Section",
            "confirm_delete_title" to "Confirm Deletion",
            "confirm_delete_msg" to "This channel will be permanently removed from the homepage.",
            "section_name" to "Section Name",
            "add_new" to "Add New",
            "edit_item" to "Edit Item",
            "url_empty" to "URL cannot be empty",
            "browse_youtube" to "Browse so YouTube can know your preferences",
            "url_hint" to "URL (https://...)"
        ),
        "tr" to mapOf(
            "lang_title" to "Dil / Language",
            "home_section" to "Ana sayfa bölümlerini değiştir",
            "trending" to "Trendler",
            "manage_channels" to "Ana Sayfa Kanallarını Yönet",
            "manage_channels_sum" to "Özel kanal ve oynatma listesi ekle, düzenle",
            "account_section" to "Hesap ve Çerezler",
            "login_btn" to "Giriş / Çerezleri Güncelle",
            "login_sum" to "Oturum çerezlerini yakalamak için Google ile giriş yapın",
            "status_title" to "Hesap Durumu",
            "status_logged_in" to "Giriş Yapıldı (Çerezler Aktif)",
            "status_logged_out" to "Giriş Yapılmadı (Gizli Mod)",
            "visitor_id" to "Ziyaretçi Kimliği",
            "edit_manual" to "Manuel Düzenle",
            "logout_btn" to "Çıkış Yap (Çerezleri Temizle)",
            "logout_confirm_title" to "Çıkışı Onayla",
            "logout_confirm_msg" to "Çıkış yapmak ve tüm çerezleri temizlemek istediğinize emin misiniz?",
            "browsing_section" to "Tarama ve Arama",
            "player_engine" to "Oynatıcı Motoru",
            "player_advanced" to "Gelişmiş (1080p/4K + Oto-Çeviri)",
            "player_classic" to "Klasik (Bulut Akışı Yerleşik)",
            "pages_limit" to "Kanal Sayfa Sınırı",
            "pages_sum" to "Bir kanal açıldığında getirilen sayfalar",
            "playlist_tag" to "Oynatma Listesi Arama Etiketi",
            "tag_hint" to "Etiket girin (örn. {p})",
            "current" to "Geçerli: ",
            "saved_msg" to "Giriş verileri başarıyla kaydedildi",
            "cleared_msg" to "Veriler temizlendi",
            "close" to "Kapat",
            "save" to "Kaydet",
            "ok" to "Tamam",
            "cancel" to "İptal",
            "delete" to "Sil",
            "youtube_login" to "YouTube Girişi",
            "no_data" to "Veri bulunamadı!",
            "add_channel_btn" to "+ Kanal / Liste Ekle",
            "no_channels" to "Henüz kanal eklenmedi.",
            "unnamed_section" to "İsimsiz Bölüm",
            "confirm_delete_title" to "Silmeyi Onayla",
            "confirm_delete_msg" to "Bu kanal ana sayfadan kalıcı olarak kaldırılacaktır.",
            "section_name" to "Bölüm Adı",
            "add_new" to "Yeni Ekle",
            "edit_item" to "Öğeyi Düzenle",
            "url_empty" to "URL boş olamaz",
            "browse_youtube" to "YouTube'un tercihlerinizi bilmesi için göz atın",
            "url_hint" to "URL (https://...)"
        ),
        "es" to mapOf(
            "lang_title" to "Idioma / Language",
            "home_section" to "Cambiar secciones de inicio",
            "trending" to "Tendencias",
            "manage_channels" to "Administrar Canales",
            "manage_channels_sum" to "Añadir, editar o reordenar canales personalizados",
            "account_section" to "Cuenta y Cookies",
            "login_btn" to "Iniciar sesión / Actualizar Cookies",
            "login_sum" to "Inicia sesión con Google para capturar cookies",
            "status_title" to "Estado de la cuenta",
            "status_logged_in" to "Sesión Iniciada (Cookies Activas)",
            "status_logged_out" to "Sesión No Iniciada (Incógnito)",
            "visitor_id" to "ID de visitante",
            "edit_manual" to "Editar Manualmente",
            "logout_btn" to "Cerrar sesión (Borrar Cookies)",
            "logout_confirm_title" to "Confirmar cierre de sesión",
            "logout_confirm_msg" to "¿Estás seguro de que quieres cerrar sesión y borrar todas las cookies?",
            "browsing_section" to "Navegación y Búsqueda",
            "player_engine" to "Motor del reproductor",
            "player_advanced" to "Avanzado (1080p/4K + Auto-Traducción)",
            "player_classic" to "Clásico (Integrado)",
            "pages_limit" to "Límite de páginas del canal",
            "pages_sum" to "Páginas obtenidas al abrir un canal",
            "playlist_tag" to "Etiqueta de búsqueda de Playlist",
            "tag_hint" to "Introduce etiqueta (ej. {p})",
            "current" to "Actual: ",
            "saved_msg" to "Datos guardados correctamente",
            "cleared_msg" to "Datos borrados",
            "close" to "Cerrar",
            "save" to "Guardar",
            "ok" to "Aceptar",
            "cancel" to "Cancelar",
            "delete" to "Eliminar",
            "youtube_login" to "Inicio de sesión de YouTube",
            "no_data" to "¡No se encontraron datos!",
            "add_channel_btn" to "+ Añadir Canal / Playlist",
            "no_channels" to "Aún no se han añadido canales.",
            "unnamed_section" to "Sección sin nombre",
            "confirm_delete_title" to "Confirmar eliminación",
            "confirm_delete_msg" to "Este canal se eliminará permanentemente de la página de inicio.",
            "section_name" to "Nombre de la sección",
            "add_new" to "Añadir Nuevo",
            "edit_item" to "Editar",
            "url_empty" to "La URL no puede estar vacía",
            "browse_youtube" to "Navega para que YouTube conozca tus preferencias",
            "url_hint" to "URL (https://...)"
        ),

        "de" to mapOf(
            "lang_title" to "Sprache / Language",
            "home_section" to "Startseitenbereiche ändern",
            "trending" to "Trends",
            "manage_channels" to "Startseitenkanäle verwalten",
            "manage_channels_sum" to "Benutzerdefinierte Kanäle und Playlists hinzufügen, bearbeiten oder neu anordnen",
            "account_section" to "Konto & Cookies",
            "login_btn" to "Anmelden / Cookies aktualisieren",
            "login_sum" to "Melden Sie sich mit Google an, um Sitzungscookies zu erfassen",
            "status_title" to "Kontostatus",
            "status_logged_in" to "Angemeldet (Cookies aktiv)",
            "status_logged_out" to "Nicht angemeldet (Inkognito)",
            "visitor_id" to "Besucher-ID",
            "edit_manual" to "Manuell bearbeiten",
            "logout_btn" to "Abmelden (Cookies löschen)",
            "logout_confirm_title" to "Abmeldung bestätigen",
            "logout_confirm_msg" to "Sind Sie sicher, dass Sie sich abmelden und alle Cookies löschen möchten?",
            "browsing_section" to "Browsing & Suche",
            "player_engine" to "Player-Engine",
            "player_advanced" to "Erweitert (1080p/4K + Auto-Übersetzung)",
            "player_classic" to "Klassisch (CloudStream integriert)",
            "pages_limit" to "Seitenlimit für Kanäle",
            "pages_sum" to "Seiten, die beim Öffnen eines Kanals abgerufen werden",
            "playlist_tag" to "Playlist-Such-Tag",
            "tag_hint" to "Tag eingeben (z.B. {p})",
            "current" to "Aktuell: ",
            "saved_msg" to "Anmeldedaten erfolgreich gespeichert",
            "cleared_msg" to "Daten gelöscht",
            "close" to "Schließen",
            "save" to "Speichern",
            "ok" to "OK",
            "cancel" to "Abbrechen",
            "delete" to "Löschen",
            "youtube_login" to "YouTube-Anmeldung",
            "no_data" to "Keine Daten gefunden!",
            "add_channel_btn" to "+ Kanal / Playlist hinzufügen",
            "no_channels" to "Noch keine Kanäle hinzugefügt.",
            "unnamed_section" to "Unbenannter Abschnitt",
            "confirm_delete_title" to "Löschen bestätigen",
            "confirm_delete_msg" to "Dieser Kanal wird dauerhaft von der Startseite entfernt.",
            "section_name" to "Abschnittsname",
            "add_new" to "Neu hinzufügen",
            "edit_item" to "Element bearbeiten",
            "url_empty" to "URL darf nicht leer sein",
            "browse_youtube" to "Stöbern Sie, damit YouTube Ihre Vorlieben kennenlernt",
            "url_hint" to "URL (https://...)"
        ),
        "fr" to mapOf(
            "lang_title" to "Langue / Language",
            "home_section" to "Modifier les sections de la page d'accueil",
            "trending" to "Tendances",
            "manage_channels" to "Gérer les chaînes de la page d'accueil",
            "manage_channels_sum" to "Ajouter, modifier ou réorganiser des chaînes et playlists personnalisées",
            "account_section" to "Compte et Cookies",
            "login_btn" to "Connexion / Mettre à jour les cookies",
            "login_sum" to "Connectez-vous avec Google pour capturer les cookies de session",
            "status_title" to "État du compte",
            "status_logged_in" to "Connecté (Cookies actifs)",
            "status_logged_out" to "Non connecté (Incognito)",
            "visitor_id" to "ID Visiteur",
            "edit_manual" to "Modifier manuellement",
            "logout_btn" to "Déconnexion (Effacer les cookies)",
            "logout_confirm_title" to "Confirmer la déconnexion",
            "logout_confirm_msg" to "Êtes-vous sûr de vouloir vous déconnecter et effacer tous les cookies ?",
            "browsing_section" to "Navigation et recherche",
            "player_engine" to "Moteur de lecteur",
            "player_advanced" to "Avancé (1080p/4K + Traduction auto)",
            "player_classic" to "Classique (Intégré à CloudStream)",
            "pages_limit" to "Limite de pages par chaîne",
            "pages_sum" to "Pages récupérées à l'ouverture d'une chaîne",
            "playlist_tag" to "Tag de recherche de playlist",
            "tag_hint" to "Entrez le tag (ex: {p})",
            "current" to "Actuel : ",
            "saved_msg" to "Données de connexion enregistrées avec succès",
            "cleared_msg" to "Données effacées",
            "close" to "Fermer",
            "save" to "Enregistrer",
            "ok" to "OK",
            "cancel" to "Annuler",
            "delete" to "Supprimer",
            "youtube_login" to "Connexion YouTube",
            "no_data" to "Aucune donnée trouvée !",
            "add_channel_btn" to "+ Ajouter une chaîne / playlist",
            "no_channels" to "Aucune chaîne ajoutée pour le moment.",
            "unnamed_section" to "Section sans nom",
            "confirm_delete_title" to "Confirmer la suppression",
            "confirm_delete_msg" to "Cette chaîne sera définitivement supprimée de la page d'accueil.",
            "section_name" to "Nom de la section",
            "add_new" to "Ajouter",
            "edit_item" to "Modifier l'élément",
            "url_empty" to "L'URL ne peut pas être vide",
            "browse_youtube" to "Naviguez pour que YouTube connaisse vos préférences",
            "url_hint" to "URL (https://...)"
        ),
        "ja" to mapOf(
            "lang_title" to "言語 / Language",
            "home_section" to "ホームページのセクションを変更",
            "trending" to "急上昇",
            "manage_channels" to "ホームページチャンネルの管理",
            "manage_channels_sum" to "カスタムチャンネルや再生リストの追加、編集、並べ替え",
            "account_section" to "アカウントとCookie",
            "login_btn" to "ログイン / Cookieを更新",
            "login_sum" to "GoogleでサインインしてセッションCookieを取得します",
            "status_title" to "アカウントの状態",
            "status_logged_in" to "ログイン済み（Cookie有効）",
            "status_logged_out" to "未ログイン（シークレット）",
            "visitor_id" to "ビジターID",
            "edit_manual" to "手動で編集",
            "logout_btn" to "ログアウト（Cookieを消去）",
            "logout_confirm_title" to "ログアウトの確認",
            "logout_confirm_msg" to "本当にログアウトしてすべてのCookieを消去しますか？",
            "browsing_section" to "ブラウジングと検索",
            "player_engine" to "プレーヤーエンジン",
            "player_advanced" to "高度（1080p/4K + 自動翻訳）",
            "player_classic" to "クラシック（CloudStream内蔵）",
            "pages_limit" to "チャンネルのページ数制限",
            "pages_sum" to "チャンネルを開いたときに取得されるページ数",
            "playlist_tag" to "再生リスト検索タグ",
            "tag_hint" to "タグを入力（例：{p}）",
            "current" to "現在：",
            "saved_msg" to "ログインデータが正常に保存されました",
            "cleared_msg" to "データが消去されました",
            "close" to "閉じる",
            "save" to "保存",
            "ok" to "OK",
            "cancel" to "キャンセル",
            "delete" to "削除",
            "youtube_login" to "YouTubeログイン",
            "no_data" to "データが見つかりません！",
            "add_channel_btn" to "+ チャンネル/再生リストを追加",
            "no_channels" to "まだチャンネルが追加されていません。",
            "unnamed_section" to "無名のセクション",
            "confirm_delete_title" to "削除の確認",
            "confirm_delete_msg" to "このチャンネルはホームページから永久に削除されます。",
            "section_name" to "セクション名",
            "add_new" to "新規追加",
            "edit_item" to "アイテムを編集",
            "url_empty" to "URLは空にできません",
            "browse_youtube" to "YouTubeがあなたの好みを学習できるように閲覧してください",
            "url_hint" to "URL (https://...)"
        ),
        "ru" to mapOf(
            "lang_title" to "Язык / Language",
            "home_section" to "Изменить разделы главной страницы",
            "trending" to "В тренде",
            "manage_channels" to "Управление каналами на главной",
            "manage_channels_sum" to "Добавляйте, редактируйте или изменяйте порядок каналов и плейлистов",
            "account_section" to "Аккаунт и файлы cookie",
            "login_btn" to "Войти / Обновить cookie",
            "login_sum" to "Войдите через Google, чтобы получить сессионные cookie",
            "status_title" to "Статус аккаунта",
            "status_logged_in" to "Вход выполнен (Cookie активны)",
            "status_logged_out" to "Вход не выполнен (Инкогнито)",
            "visitor_id" to "ID посетителя",
            "edit_manual" to "Редактировать вручную",
            "logout_btn" to "Выйти (Очистить cookie)",
            "logout_confirm_title" to "Подтвердить выход",
            "logout_confirm_msg" to "Вы уверены, что хотите выйти и очистить все файлы cookie?",
            "browsing_section" to "Просмотр и поиск",
            "player_engine" to "Движок плеера",
            "player_advanced" to "Продвинутый (1080p/4K + автоперевод)",
            "player_classic" to "Классический (встроенный в CloudStream)",
            "pages_limit" to "Лимит страниц канала",
            "pages_sum" to "Количество страниц, загружаемых при открытии канала",
            "playlist_tag" to "Тег для поиска плейлистов",
            "tag_hint" to "Введите тег (например, {p})",
            "current" to "Текущий: ",
            "saved_msg" to "Данные для входа успешно сохранены",
            "cleared_msg" to "Данные очищены",
            "close" to "Закрыть",
            "save" to "Сохранить",
            "ok" to "ОК",
            "cancel" to "Отмена",
            "delete" to "Удалить",
            "youtube_login" to "Вход в YouTube",
            "no_data" to "Данные не найдены!",
            "add_channel_btn" to "+ Добавить канал / плейлист",
            "no_channels" to "Каналы еще не добавлены.",
            "unnamed_section" to "Раздел без названия",
            "confirm_delete_title" to "Подтвердить удаление",
            "confirm_delete_msg" to "Этот канал будет навсегда удален с главной страницы.",
            "section_name" to "Название раздела",
            "add_new" to "Добавить новый",
            "edit_item" to "Редактировать",
            "url_empty" to "URL не может быть пустым",
            "browse_youtube" to "Просматривайте, чтобы YouTube узнал ваши предпочтения",
            "url_hint" to "URL (https://...)"
        ),
        "pt" to mapOf(
            "lang_title" to "Idioma / Language",
            "home_section" to "Alterar seções da página inicial",
            "trending" to "Em alta",
            "manage_channels" to "Gerenciar Canais da Página Inicial",
            "manage_channels_sum" to "Adicione, edite ou reordene canais e playlists personalizados",
            "account_section" to "Conta e Cookies",
            "login_btn" to "Login / Atualizar Cookies",
            "login_sum" to "Faça login com o Google para capturar os cookies da sessão",
            "status_title" to "Status da Conta",
            "status_logged_in" to "Logado (Cookies Ativos)",
            "status_logged_out" to "Não Logado (Anônimo)",
            "visitor_id" to "ID de Visitante",
            "edit_manual" to "Editar Manualmente",
            "logout_btn" to "Logout (Limpar Cookies)",
            "logout_confirm_title" to "Confirmar Logout",
            "logout_confirm_msg" to "Tem certeza de que deseja sair и limpar todos os cookies?",
            "browsing_section" to "Navegação e Pesquisa",
            "player_engine" to "Mecanismo do Player",
            "player_advanced" to "Avançado (1080p/4K + Tradução Automática)",
            "player_classic" to "Clássico (Integrado ao CloudStream)",
            "pages_limit" to "Limite de Páginas do Canal",
            "pages_sum" to "Páginas buscadas ao abrir um canal",
            "playlist_tag" to "Tag de Pesquisa de Playlist",
            "tag_hint" to "Digite a tag (ex: {p})",
            "current" to "Atual: ",
            "saved_msg" to "Dados de login salvos com sucesso",
            "cleared_msg" to "Dados limpos",
            "close" to "Fechar",
            "save" to "Salvar",
            "ok" to "OK",
            "cancel" to "Cancelar",
            "delete" to "Excluir",
            "youtube_login" to "Login do YouTube",
            "no_data" to "Nenhum dado encontrado!",
            "add_channel_btn" to "+ Adicionar Canal / Playlist",
            "no_channels" to "Nenhum canal adicionado ainda.",
            "unnamed_section" to "Seção Sem Nome",
            "confirm_delete_title" to "Confirmar Exclusão",
            "confirm_delete_msg" to "Este canal será removido permanentemente da página inicial.",
            "section_name" to "Nome da Seção",
            "add_new" to "Adicionar Novo",
            "edit_item" to "Editar Item",
            "url_empty" to "A URL não pode estar vazia",
            "browse_youtube" to "Navegue para que o YouTube conheça suas preferências",
            "url_hint" to "URL (https://...)"
        ),
        "it" to mapOf(
            "lang_title" to "Lingua / Language",
            "home_section" to "Modifica sezioni della homepage",
            "trending" to "Tendenze",
            "manage_channels" to "Gestisci Canali Homepage",
            "manage_channels_sum" to "Aggiungi, modifica o riordina canali e playlist personalizzati",
            "account_section" to "Account e Cookie",
            "login_btn" to "Accedi / Aggiorna Cookie",
            "login_sum" to "Accedi con Google per catturare i cookie di sessione",
            "status_title" to "Stato Account",
            "status_logged_in" to "Connesso (Cookie Attivi)",
            "status_logged_out" to "Non connesso (Incognito)",
            "visitor_id" to "ID Visitatore",
            "edit_manual" to "Modifica Manualmente",
            "logout_btn" to "Logout (Cancella Cookie)",
            "logout_confirm_title" to "Conferma Logout",
            "logout_confirm_msg" to "Sei sicuro di voler effettuare il logout e cancellare tutti i cookie?",
            "browsing_section" to "Navigazione e Ricerca",
            "player_engine" to "Motore del Lettore",
            "player_advanced" to "Avanzato (1080p/4K + Traduzione Automatica)",
            "player_classic" to "Classico (Integrato in CloudStream)",
            "pages_limit" to "Limite Pagine Canale",
            "pages_sum" to "Pagine caricate all'apertura di un canale",
            "playlist_tag" to "Tag Ricerca Playlist",
            "tag_hint" to "Inserisci tag (es. {p})",
            "current" to "Attuale: ",
            "saved_msg" to "Dati di accesso salvati con successo",
            "cleared_msg" to "Dati cancellati",
            "close" to "Chiudi",
            "save" to "Salva",
            "ok" to "OK",
            "cancel" to "Annulla",
            "delete" to "Elimina",
            "youtube_login" to "Accesso a YouTube",
            "no_data" to "Nessun dato trovato!",
            "add_channel_btn" to "+ Aggiungi Canale / Playlist",
            "no_channels" to "Nessun canale ancora aggiunto.",
            "unnamed_section" to "Sezione senza nome",
            "confirm_delete_title" to "Conferma Eliminazione",
            "confirm_delete_msg" to "Questo canale verrà rimosso definitivamente dalla homepage.",
            "section_name" to "Nome Sezione",
            "add_new" to "Aggiungi Nuovo",
            "edit_item" to "Modifica Elemento",
            "url_empty" to "L'URL non può essere vuoto",
            "browse_youtube" to "Naviga in modo che YouTube possa conoscere le tue preferenze",
            "url_hint" to "URL (https://...)"
        ),
        "id" to mapOf(
            "lang_title" to "Bahasa / Language",
            "home_section" to "Ubah bagian beranda",
            "trending" to "Sedang Tren",
            "manage_channels" to "Kelola Saluran Beranda",
            "manage_channels_sum" to "Tambah, edit, atau urutkan ulang saluran dan playlist khusus",
            "account_section" to "Akun & Cookie",
            "login_btn" to "Masuk / Perbarui Cookie",
            "login_sum" to "Masuk dengan Google untuk mengambil cookie sesi",
            "status_title" to "Status Akun",
            "status_logged_in" to "Sudah Masuk (Cookie Aktif)",
            "status_logged_out" to "Belum Masuk (Penyamaran)",
            "visitor_id" to "ID Pengunjung",
            "edit_manual" to "Edit Manual",
            "logout_btn" to "Keluar (Hapus Cookie)",
            "logout_confirm_title" to "Konfirmasi Keluar",
            "logout_confirm_msg" to "Apakah Anda yakin ingin keluar dan menghapus semua cookie?",
            "browsing_section" to "Penjelajahan & Pencarian",
            "player_engine" to "Mesin Pemutar",
            "player_advanced" to "Lanjutan (1080p/4K + Terjemahan Otomatis)",
            "player_classic" to "Klasik (Bawaan CloudStream)",
            "pages_limit" to "Batas Halaman Saluran",
            "pages_sum" to "Halaman yang diambil saat membuka saluran",
            "playlist_tag" to "Tag Pencarian Playlist",
            "tag_hint" to "Masukkan tag (mis. {p})",
            "current" to "Saat ini: ",
            "saved_msg" to "Data login berhasil disimpan",
            "cleared_msg" to "Data dihapus",
            "close" to "Tutup",
            "save" to "Simpan",
            "ok" to "OK",
            "cancel" to "Batal",
            "delete" to "Hapus",
            "youtube_login" to "Login YouTube",
            "no_data" to "Tidak ada data yang ditemukan!",
            "add_channel_btn" to "+ Tambah Saluran / Playlist",
            "no_channels" to "Belum ada saluran yang ditambahkan.",
            "unnamed_section" to "Bagian Tanpa Nama",
            "confirm_delete_title" to "Konfirmasi Penghapusan",
            "confirm_delete_msg" to "Saluran ini akan dihapus secara permanen dari beranda.",
            "section_name" to "Nama Bagian",
            "add_new" to "Tambah Baru",
            "edit_item" to "Edit Item",
            "url_empty" to "URL tidak boleh kosong",
            "browse_youtube" to "Jelajahi agar YouTube dapat mengetahui preferensi Anda",
            "url_hint" to "URL (https://...)"
        ),
        "pl" to mapOf(
            "lang_title" to "Język / Language",
            "home_section" to "Zmień sekcje strony głównej",
            "trending" to "Na czasie",
            "manage_channels" to "Zarządzaj kanałami na stronie głównej",
            "manage_channels_sum" to "Dodawaj, edytuj lub zmieniaj kolejność niestandardowych kanałów i playlist",
            "account_section" to "Konto i Ciasteczka",
            "login_btn" to "Zaloguj / Zaktualizuj ciasteczka",
            "login_sum" to "Zaloguj się przez Google, aby przechwycić ciasteczka sesji",
            "status_title" to "Status konta",
            "status_logged_in" to "Zalogowano (Ciasteczka aktywne)",
            "status_logged_out" to "Niezalogowano (Incognito)",
            "visitor_id" to "ID odwiedzającego",
            "edit_manual" to "Edytuj ręcznie",
            "logout_btn" to "Wyloguj (Wyczyść ciasteczka)",
            "logout_confirm_title" to "Potwierdź wylogowanie",
            "logout_confirm_msg" to "Czy na pewno chcesz się wylogować i wyczyścić wszystkie ciasteczka?",
            "browsing_section" to "Przeglądanie i wyszukiwanie",
            "player_engine" to "Silnik odtwarzacza",
            "player_advanced" to "Zaawansowany (1080p/4K + Autotłumaczenie)",
            "player_classic" to "Klasyczny (Wbudowany w CloudStream)",
            "pages_limit" to "Limit stron kanału",
            "pages_sum" to "Strony pobierane przy otwieraniu kanału",
            "playlist_tag" to "Tag wyszukiwania playlist",
            "tag_hint" to "Wprowadź tag (np. {p})",
            "current" to "Obecny: ",
            "saved_msg" to "Dane logowania zapisane pomyślnie",
            "cleared_msg" to "Dane wyczyszczone",
            "close" to "Zamknij",
            "save" to "Zapisz",
            "ok" to "OK",
            "cancel" to "Anuluj",
            "delete" to "Usuń",
            "youtube_login" to "Logowanie YouTube",
            "no_data" to "Nie znaleziono danych!",
            "add_channel_btn" to "+ Dodaj kanał / playlistę",
            "no_channels" to "Nie dodano jeszcze żadnych kanałów.",
            "unnamed_section" to "Sekcja bez nazwy",
            "confirm_delete_title" to "Potwierdź usunięcie",
            "confirm_delete_msg" to "Ten kanał zostanie trwale usunięty ze strony głównej.",
            "section_name" to "Nazwa sekcji",
            "add_new" to "Dodaj nowy",
            "edit_item" to "Edytuj element",
            "url_empty" to "URL nie może być pusty",
            "browse_youtube" to "Przeglądaj, aby YouTube poznał Twoje preferencje",
            "url_hint" to "URL (https://...)"
        ),


        "fa" to mapOf(
            "lang_title" to "زبان / Language",
            "home_section" to "تغییر بخش‌های صفحه اصلی",
            "trending" to "پرطرفدار",
            "manage_channels" to "مدیریت کانال‌های صفحه اصلی",
            "manage_channels_sum" to "افزودن، ویرایش یا مرتب‌سازی کانال‌ها و لیست‌های پخش سفارشی",
            "account_section" to "حساب و کوکی‌ها",
            "login_btn" to "ورود / به‌روزرسانی کوکی‌ها",
            "login_sum" to "برای دریافت کوکی‌های جلسه، با حساب گوگل خود وارد شوید",
            "status_title" to "وضعیت حساب",
            "status_logged_in" to "وارد شده (کوکی‌ها فعال)",
            "status_logged_out" to "وارد نشده (ناشناس)",
            "visitor_id" to "شناسه بازدیدکننده",
            "edit_manual" to "ویرایش دستی",
            "logout_btn" to "خروج (پاک کردن کوکی‌ها)",
            "logout_confirm_title" to "تأیید خروج",
            "logout_confirm_msg" to "آیا مطمئن هستید که می‌خواهید خارج شوید و تمام کوکی‌ها را پاک کنید؟",
            "browsing_section" to "مرور و جستجو",
            "player_engine" to "موتور پخش‌کننده",
            "player_advanced" to "پیشرفته (1080p/4K + ترجمه خودکار)",
            "player_classic" to "کلاسیک (درون‌ساخت CloudStream)",
            "pages_limit" to "محدودیت صفحات کانال",
            "pages_sum" to "صفحاتی که هنگام باز کردن کانال دریافت می‌شوند",
            "playlist_tag" to "برچسب جستجوی لیست پخش",
            "tag_hint" to "برچسب را وارد کنید (مثال: {p})",
            "current" to "فعلی: ",
            "saved_msg" to "اطلاعات ورود با موفقیت ذخیره شد",
            "cleared_msg" to "داده‌ها پاک شد",
            "close" to "بستن",
            "save" to "ذخیره",
            "ok" to "باشه",
            "cancel" to "لغو",
            "delete" to "حذف",
            "youtube_login" to "ورود به یوتیوب",
            "no_data" to "داده‌ای یافت نشد!",
            "add_channel_btn" to "+ افزودن کانال / لیست پخش",
            "no_channels" to "هنوز کانالی اضافه نشده است.",
            "unnamed_section" to "بخش بدون نام",
            "confirm_delete_title" to "تأیید حذف",
            "confirm_delete_msg" to "این کانال برای همیشه از صفحه اصلی حذف خواهد شد.",
            "section_name" to "نام بخش",
            "add_new" to "افزودن جدید",
            "edit_item" to "ویرایش مورد",
            "url_empty" to "URL نمی‌تواند خالی باشد",
            "browse_youtube" to "مرور کنید تا یوتیوب با سلیقه شما آشنا شود",
            "url_hint" to "URL (https://...)"
        ),
        "hi" to mapOf(
            "lang_title" to "भाषा / Language",
            "home_section" to "मुखपृष्ठ अनुभाग बदलें",
            "trending" to "ट्रेंडिंग",
            "manage_channels" to "मुखपृष्ठ चैनल प्रबंधित करें",
            "manage_channels_sum" to "कस्टम चैनल और प्लेलिस्ट जोड़ें, संपादित करें, या पुनः व्यवस्थित करें",
            "account_section" to "खाता और कुकीज़",
            "login_btn" to "लॉगिन / कुकीज़ अपडेट करें",
            "login_sum" to "सत्र कुकीज़ कैप्चर करने के लिए Google से साइन इन करें",
            "status_title" to "खाते की स्थिति",
            "status_logged_in" to "लॉग इन (कुकीज़ सक्रिय)",
            "status_logged_out" to "लॉग इन नहीं (इंकॉग्निटो)",
            "visitor_id" to "आगंतुक आईडी",
            "edit_manual" to "मैन्युअल रूप से संपादित करें",
            "logout_btn" to "लॉगआउट (कुकीज़ साफ़ करें)",
            "logout_confirm_title" to "लॉगआउट की पुष्टि करें",
            "logout_confirm_msg" to "क्या आप वाकई लॉग आउट करना और सभी कुकीज़ साफ़ करना चाहते हैं?",
            "browsing_section" to "ब्राउज़िंग और खोज",
            "player_engine" to "प्लेयर इंजन",
            "player_advanced" to "उन्नत (1080p/4K + स्वतः-अनुवाद)",
            "player_classic" to "क्लासिक (CloudStream बिल्ट-इन)",
            "pages_limit" to "चैनल पेज सीमा",
            "pages_sum" to "चैनल खोलने पर प्राप्त पेज",
            "playlist_tag" to "प्लेलिस्ट खोज टैग",
            "tag_hint" to "टैग दर्ज करें (जैसे {p})",
            "current" to "वर्तमान: ",
            "saved_msg" to "लॉगिन डेटा सफलतापूर्वक सहेजा गया",
            "cleared_msg" to "डेटा साफ़ किया गया",
            "close" to "बंद करें",
            "save" to "सहेजें",
            "ok" to "ठीक है",
            "cancel" to "रद्द करें",
            "delete" to "हटाएं",
            "youtube_login" to "यूट्यूब लॉगिन",
            "no_data" to "कोई डेटा नहीं मिला!",
            "add_channel_btn" to "+ चैनल / प्लेलिस्ट जोड़ें",
            "no_channels" to "अभी तक कोई चैनल नहीं जोड़ा गया है।",
            "unnamed_section" to "अनाम अनुभाग",
            "confirm_delete_title" to "हटाने की पुष्टि करें",
            "confirm_delete_msg" to "यह चैनल मुखपृष्ठ से स्थायी रूप से हटा दिया जाएगा।",
            "section_name" to "अनुभाग का नाम",
            "add_new" to "नया जोड़ें",
            "edit_item" to "आइटम संपादित करें",
            "url_empty" to "URL खाली नहीं हो सकता",
            "browse_youtube" to "ब्राउज़ करें ताकि यूट्यूब आपकी पसंद जान सके",
            "url_hint" to "URL (https://...)"
        ),
        "ko" to mapOf(
            "lang_title" to "언어 / Language",
            "home_section" to "홈페이지 섹션 변경",
            "trending" to "인기",
            "manage_channels" to "홈페이지 채널 관리",
            "manage_channels_sum" to "사용자 지정 채널 및 재생 목록 추가, 편집 또는 재정렬",
            "account_section" to "계정 및 쿠키",
            "login_btn" to "로그인 / 쿠키 업데이트",
            "login_sum" to "세션 쿠키를 캡처하려면 Google로 로그인하세요",
            "status_title" to "계정 상태",
            "status_logged_in" to "로그인됨 (쿠키 활성)",
            "status_logged_out" to "로그인되지 않음 (시크릿)",
            "visitor_id" to "방문자 ID",
            "edit_manual" to "수동 편집",
            "logout_btn" to "로그아웃 (쿠키 지우기)",
            "logout_confirm_title" to "로그아웃 확인",
            "logout_confirm_msg" to "정말로 로그아웃하고 모든 쿠키를 지우시겠습니까?",
            "browsing_section" to "탐색 및 검색",
            "player_engine" to "플레이어 엔진",
            "player_advanced" to "고급 (1080p/4K + 자동 번역)",
            "player_classic" to "클래식 (CloudStream 내장)",
            "pages_limit" to "채널 페이지 제한",
            "pages_sum" to "채널을 열 때 가져오는 페이지",
            "playlist_tag" to "재생 목록 검색 태그",
            "tag_hint" to "태그 입력 (예: {p})",
            "current" to "현재: ",
            "saved_msg" to "로그인 데이터가 성공적으로 저장되었습니다",
            "cleared_msg" to "데이터가 지워졌습니다",
            "close" to "닫기",
            "save" to "저장",
            "ok" to "확인",
            "cancel" to "취소",
            "delete" to "삭제",
            "youtube_login" to "YouTube 로그인",
            "no_data" to "데이터를 찾을 수 없습니다!",
            "add_channel_btn" to "+ 채널 / 재생 목록 추가",
            "no_channels" to "아직 추가된 채널이 없습니다.",
            "unnamed_section" to "이름 없는 섹션",
            "confirm_delete_title" to "삭제 확인",
            "confirm_delete_msg" to "이 채널은 홈페이지에서 영구적으로 제거됩니다.",
            "section_name" to "섹션 이름",
            "add_new" to "새로 추가",
            "edit_item" to "항목 편집",
            "url_empty" to "URL은 비워 둘 수 없습니다",
            "browse_youtube" to "YouTube가 귀하의 선호를 알 수 있도록 탐색하세요",
            "url_hint" to "URL (https://...)"
        ),
        "zh" to mapOf(
            "lang_title" to "语言 / Language",
            "home_section" to "更改主页部分",
            "trending" to "热门",
            "manage_channels" to "管理主页频道",
            "manage_channels_sum" to "添加、编辑或重新排序自定义频道和播放列表",
            "account_section" to "帐户和 Cookie",
            "login_btn" to "登录 / 更新 Cookie",
            "login_sum" to "使用 Google 登录以捕获会话 Cookie",
            "status_title" to "帐户状态",
            "status_logged_in" to "已登录 (Cookie 有效)",
            "status_logged_out" to "未登录 (无痕模式)",
            "visitor_id" to "访客 ID",
            "edit_manual" to "手动编辑",
            "logout_btn" to "登出 (清除 Cookie)",
            "logout_confirm_title" to "确认登出",
            "logout_confirm_msg" to "您确定要登出并清除所有 Cookie 吗？",
            "browsing_section" to "浏览和搜索",
            "player_engine" to "播放器引擎",
            "player_advanced" to "高级 (1080p/4K + 自动翻译)",
            "player_classic" to "经典 (CloudStream 内置)",
            "pages_limit" to "频道页面限制",
            "pages_sum" to "打开频道时获取的页面",
            "playlist_tag" to "播放列表搜索标签",
            "tag_hint" to "输入标签 (例如 {p})",
            "current" to "当前: ",
            "saved_msg" to "登录数据已成功保存",
            "cleared_msg" to "数据已清除",
            "close" to "关闭",
            "save" to "保存",
            "ok" to "确定",
            "cancel" to "取消",
            "delete" to "删除",
            "youtube_login" to "YouTube 登录",
            "no_data" to "未找到数据！",
            "add_channel_btn" to "+ 添加频道 / 播放列表",
            "no_channels" to "尚未添加任何频道。",
            "unnamed_section" to "未命名部分",
            "confirm_delete_title" to "确认删除",
            "confirm_delete_msg" to "此频道将从主页永久删除。",
            "section_name" to "部分名称",
            "add_new" to "新增",
            "edit_item" to "编辑项目",
            "url_empty" to "URL 不能为空",
            "browse_youtube" to "浏览以便 YouTube 了解您的偏好",
            "url_hint" to "URL (https://...)"
        ),

        "bn" to mapOf(
            "lang_title" to "ভাষা / Language",
            "home_section" to "হোমপেজ বিভাগ পরিবর্তন করুন",
            "trending" to "ট্রেন্ডিং",
            "manage_channels" to "হোমপেজ চ্যানেল পরিচালনা করুন",
            "manage_channels_sum" to "কাস্টম চ্যানেল এবং প্লেলিস্ট যোগ করুন, সম্পাদনা করুন বা পুনরায় সাজান",
            "account_section" to "অ্যাকাউন্ট এবং কুকিজ",
            "login_btn" to "লগইন / কুকিজ আপডেট করুন",
            "login_sum" to "সেশন কুকিজ ক্যাপচার করতে Google দিয়ে সাইন ইন করুন",
            "status_title" to "অ্যাকাউন্টের স্থিতি",
            "status_logged_in" to "লগ ইন করা হয়েছে (কুকিজ সক্রিয়)",
            "status_logged_out" to "লগ ইন করা হয়নি (ইনকগনিটো)",
            "visitor_id" to "ভিজিটর আইডি",
            "edit_manual" to "ম্যানুয়ালি সম্পাদনা করুন",
            "logout_btn" to "লগআউট (কুকিজ মুছুন)",
            "logout_confirm_title" to "লগআউট নিশ্চিত করুন",
            "logout_confirm_msg" to "আপনি কি নিশ্চিত যে আপনি লগ আউট করতে এবং সমস্ত কুকিজ মুছতে চান?",
            "browsing_section" to "ব্রাউজিং এবং অনুসন্ধান",
            "player_engine" to "প্লেয়ার ইঞ্জিন",
            "player_advanced" to "উন্নত (1080p/4K + স্বয়ংক্রিয় অনুবাদ)",
            "player_classic" to "ক্লাসিক (ক্লাউডস্ট্রিম বিল্ট-ইন)",
            "pages_limit" to "চ্যানেল পৃষ্ঠা সীমা",
            "pages_sum" to "একটি চ্যানেল খোলার সময় আনা পৃষ্ঠাগুলি",
            "playlist_tag" to "প্লেলিস্ট অনুসন্ধান ট্যাগ",
            "tag_hint" to "ট্যাগ লিখুন (যেমন {p})",
            "current" to "বর্তমান: ",
            "saved_msg" to "লগইন ডেটা সফলভাবে সংরক্ষিত হয়েছে",
            "cleared_msg" to "ডেটা মুছে ফেলা হয়েছে",
            "close" to "বন্ধ করুন",
            "save" to "সংরক্ষণ করুন",
            "ok" to "ঠিক আছে",
            "cancel" to "বাতিল করুন",
            "delete" to "মুছুন",
            "youtube_login" to "ইউটিউব লগইন",
            "no_data" to "কোন ডেটা পাওয়া যায়নি!",
            "add_channel_btn" to "+ চ্যানেল / প্লেলিস্ট যোগ করুন",
            "no_channels" to "এখনও কোনো চ্যানেল যোগ করা হয়নি।",
            "unnamed_section" to "নামবিহীন বিভাগ",
            "confirm_delete_title" to "মুছে ফেলার বিষয়টি নিশ্চিত করুন",
            "confirm_delete_msg" to "এই চ্যানেলটি হোমপেজ থেকে স্থায়ীভাবে মুছে ফেলা হবে।",
            "section_name" to "বিভাগের নাম",
            "add_new" to "নতুন যোগ করুন",
            "edit_item" to "আইটেম সম্পাদনা করুন",
            "url_empty" to "URL খালি রাখা যাবে না",
            "browse_youtube" to "ব্রাউজ করুন যাতে YouTube আপনার পছন্দগুলি জানতে পারে",
            "url_hint" to "URL (https://...)"
        ),
        "cs" to mapOf(
            "lang_title" to "Jazyk / Language",
            "home_section" to "Změnit sekce domovské stránky",
            "trending" to "Trendy",
            "manage_channels" to "Spravovat kanály domovské stránky",
            "manage_channels_sum" to "Přidat, upravit nebo změnit pořadí vlastních kanálů a seznamů skladeb",
            "account_section" to "Účet a soubory cookie",
            "login_btn" to "Přihlásit se / Aktualizovat soubory cookie",
            "login_sum" to "Přihlaste se pomocí Googlu a získejte soubory cookie relace",
            "status_title" to "Stav účtu",
            "status_logged_in" to "Přihlášeno (cookie aktivní)",
            "status_logged_out" to "Nepřihlášeno (inkognito)",
            "visitor_id" to "ID návštěvníka",
            "edit_manual" to "Upravit ručně",
            "logout_btn" to "Odhlásit se (vymazat cookies)",
            "logout_confirm_title" to "Potvrdit odhlášení",
            "logout_confirm_msg" to "Opravdu se chcete odhlásit a vymazat všechny soubory cookie?",
            "browsing_section" to "Procházení a hledání",
            "player_engine" to "Přehrávač",
            "player_advanced" to "Pokročilý (1080p/4K + auto. překlad)",
            "player_classic" to "Klasický (vestavěný CloudStream)",
            "pages_limit" to "Limit stránek kanálu",
            "pages_sum" to "Stránky načtené při otevření kanálu",
            "playlist_tag" to "Značka vyhledávání playlistu",
            "tag_hint" to "Zadejte značku (např. {p})",
            "current" to "Aktuální: ",
            "saved_msg" to "Přihlašovací údaje byly úspěšně uloženy",
            "cleared_msg" to "Data byla vymazána",
            "close" to "Zavřít",
            "save" to "Uložit",
            "ok" to "OK",
            "cancel" to "Zrušit",
            "delete" to "Smazat",
            "youtube_login" to "Přihlášení na YouTube",
            "no_data" to "Nebyla nalezena žádná data!",
            "add_channel_btn" to "+ Přidat kanál / playlist",
            "no_channels" to "Zatím nebyly přidány žádné kanály.",
            "unnamed_section" to "Nepojmenovaná sekce",
            "confirm_delete_title" to "Potvrdit smazání",
            "confirm_delete_msg" to "Tento kanál bude trvale odstraněn z domovské stránky.",
            "section_name" to "Název sekce",
            "add_new" to "Přidat nový",
            "edit_item" to "Upravit položku",
            "url_empty" to "URL nesmí být prázdná",
            "browse_youtube" to "Procházejte, aby YouTube poznal vaše preference",
            "url_hint" to "URL (https://...)"
        ),
        "da" to mapOf(
            "lang_title" to "Sprog / Language",
            "home_section" to "Skift sektioner på startsiden",
            "trending" to "Trending",
            "manage_channels" to "Administrer startsidekanaler",
            "manage_channels_sum" to "Tilføj, rediger eller omarranger tilpassede kanaler og afspilningslister",
            "account_section" to "Konto og cookies",
            "login_btn" to "Log ind / Opdater cookies",
            "login_sum" to "Log ind med Google for at hente sessionscookies",
            "status_title" to "Kontostatus",
            "status_logged_in" to "Logget ind (Cookies aktive)",
            "status_logged_out" to "Ikke logget ind (Inkognito)",
            "visitor_id" to "Besøgende ID",
            "edit_manual" to "Rediger manuelt",
            "logout_btn" to "Log ud (Ryd cookies)",
            "logout_confirm_title" to "Bekræft log ud",
            "logout_confirm_msg" to "Er du sikker på, at du vil logge ud og rydde alle cookies?",
            "browsing_section" to "Gennemse og søg",
            "player_engine" to "Afspillermotor",
            "player_advanced" to "Avanceret (1080p/4K + automatisk oversættelse)",
            "player_classic" to "Klassisk (CloudStream indbygget)",
            "pages_limit" to "Grænse for kanalsider",
            "pages_sum" to "Sider hentet, når en kanal åbnes",
            "playlist_tag" to "Søgemærke for afspilningsliste",
            "tag_hint" to "Indtast tag (f.eks. {p})",
            "current" to "Nuværende: ",
            "saved_msg" to "Logindata gemt",
            "cleared_msg" to "Data ryddet",
            "close" to "Luk",
            "save" to "Gem",
            "ok" to "OK",
            "cancel" to "Annuller",
            "delete" to "Slet",
            "youtube_login" to "YouTube-login",
            "no_data" to "Ingen data fundet!",
            "add_channel_btn" to "+ Tilføj kanal / afspilningsliste",
            "no_channels" to "Ingen kanaler tilføjet endnu.",
            "unnamed_section" to "Unavngivet sektion",
            "confirm_delete_title" to "Bekræft sletning",
            "confirm_delete_msg" to "Denne kanal fjernes permanent fra startsiden.",
            "section_name" to "Sektionsnavn",
            "add_new" to "Tilføj ny",
            "edit_item" to "Rediger element",
            "url_empty" to "URL kan ikke være tom",
            "browse_youtube" to "Gennemse, så YouTube kan kende dine præferencer",
            "url_hint" to "URL (https://...)"
        ),
        "nl" to mapOf(
            "lang_title" to "Taal / Language",
            "home_section" to "Startpagina-secties wijzigen",
            "trending" to "Trending",
            "manage_channels" to "Startpagina-kanalen beheren",
            "manage_channels_sum" to "Aangepaste kanalen en afspeellijsten toevoegen, bewerken of opnieuw rangschikken",
            "account_section" to "Account en cookies",
            "login_btn" to "Inloggen / Cookies bijwerken",
            "login_sum" to "Log in met Google om sessiecookies vast te leggen",
            "status_title" to "Accountstatus",
            "status_logged_in" to "Ingelogd (cookies actief)",
            "status_logged_out" to "Niet ingelogd (Incognito)",
            "visitor_id" to "Bezoekers-ID",
            "edit_manual" to "Handmatig bewerken",
            "logout_btn" to "Uitloggen (Cookies wissen)",
            "logout_confirm_title" to "Uitloggen bevestigen",
            "logout_confirm_msg" to "Weet u zeker dat u wilt uitloggen en alle cookies wilt wissen?",
            "browsing_section" to "Bladeren en zoeken",
            "player_engine" to "Speler-engine",
            "player_advanced" to "Geavanceerd (1080p/4K + auto-vertaling)",
            "player_classic" to "Klassiek (CloudStream ingebouwd)",
            "pages_limit" to "Limiet kanaalpagina's",
            "pages_sum" to "Pagina's opgehaald bij het openen van een kanaal",
            "playlist_tag" to "Zoektag afspeellijst",
            "tag_hint" to "Voer tag in (bijv. {p})",
            "current" to "Huidig: ",
            "saved_msg" to "Inloggegevens succesvol opgeslagen",
            "cleared_msg" to "Gegevens gewist",
            "close" to "Sluiten",
            "save" to "Opslaan",
            "ok" to "OK",
            "cancel" to "Annuleren",
            "delete" to "Verwijderen",
            "youtube_login" to "YouTube Inloggen",
            "no_data" to "Geen gegevens gevonden!",
            "add_channel_btn" to "+ Kanaal / Afspeellijst toevoegen",
            "no_channels" to "Nog geen kanalen toegevoegd.",
            "unnamed_section" to "Naamloze sectie",
            "confirm_delete_title" to "Verwijderen bevestigen",
            "confirm_delete_msg" to "Dit kanaal wordt permanent verwijderd van de startpagina.",
            "section_name" to "Sectienaam",
            "add_new" to "Nieuwe toevoegen",
            "edit_item" to "Item bewerken",
            "url_empty" to "URL mag niet leeg zijn",
            "browse_youtube" to "Blader zodat YouTube uw voorkeuren kan leren kennen",
            "url_hint" to "URL (https://...)"
        ),
        "fi" to mapOf(
            "lang_title" to "Kieli / Language",
            "home_section" to "Muuta etusivun osioita",
            "trending" to "Nousussa",
            "manage_channels" to "Hallinnoi etusivun kanavia",
            "manage_channels_sum" to "Lisää, muokkaa tai järjestä mukautettuja kanavia ja soittolistoja",
            "account_section" to "Tili ja evästeet",
            "login_btn" to "Kirjaudu sisään / Päivitä evästeet",
            "login_sum" to "Kirjaudu sisään Googlella kaapataksesi istuntoevästeet",
            "status_title" to "Tilin tila",
            "status_logged_in" to "Kirjautunut sisään (Evästeet aktiivisia)",
            "status_logged_out" to "Ei kirjautunut sisään (Incognito)",
            "visitor_id" to "Vierailijatunnus",
            "edit_manual" to "Muokkaa manuaalisesti",
            "logout_btn" to "Kirjaudu ulos (Tyhjennä evästeet)",
            "logout_confirm_title" to "Vahvista uloskirjautuminen",
            "logout_confirm_msg" to "Oletko varma, että haluat kirjautua ulos ja tyhjentää kaikki evästeet?",
            "browsing_section" to "Selaus ja haku",
            "player_engine" to "Soittimen moottori",
            "player_advanced" to "Edistynyt (1080p/4K + automaattikäännös)",
            "player_classic" to "Klassinen (CloudStream sisäänrakennettu)",
            "pages_limit" to "Kanavasivujen rajoitus",
            "pages_sum" to "Sivut, jotka haetaan kanavaa avattaessa",
            "playlist_tag" to "Soittolistan hakutunniste",
            "tag_hint" to "Syötä tunniste (esim. {p})",
            "current" to "Nykyinen: ",
            "saved_msg" to "Kirjautumistiedot tallennettu onnistuneesti",
            "cleared_msg" to "Tiedot tyhjennetty",
            "close" to "Sulje",
            "save" to "Tallenna",
            "ok" to "OK",
            "cancel" to "Peruuta",
            "delete" to "Poista",
            "youtube_login" to "YouTube-kirjautuminen",
            "no_data" to "Tietoja ei löytynyt!",
            "add_channel_btn" to "+ Lisää kanava / soittolista",
            "no_channels" to "Kanavia ei ole vielä lisätty.",
            "unnamed_section" to "Nimetön osio",
            "confirm_delete_title" to "Vahvista poisto",
            "confirm_delete_msg" to "Tämä kanava poistetaan pysyvästi etusivulta.",
            "section_name" to "Osion nimi",
            "add_new" to "Lisää uusi",
            "edit_item" to "Muokkaa kohdetta",
            "url_empty" to "URL ei voi olla tyhjä",
            "browse_youtube" to "Selaa, jotta YouTube voi oppia asetuksesi",
            "url_hint" to "URL (https://...)"
        ),
        "el" to mapOf(
            "lang_title" to "Γλώσσα / Language",
            "home_section" to "Αλλαγή ενοτήτων αρχικής σελίδας",
            "trending" to "Τάσεις",
            "manage_channels" to "Διαχείριση καναλιών αρχικής",
            "manage_channels_sum" to "Προσθήκη, επεξεργασία ή αναδιάταξη προσαρμοσμένων καναλιών και λιστών",
            "account_section" to "Λογαριασμός & Cookies",
            "login_btn" to "Σύνδεση / Ενημέρωση Cookies",
            "login_sum" to "Συνδεθείτε με το Google για λήψη cookies συνεδρίας",
            "status_title" to "Κατάσταση Λογαριασμού",
            "status_logged_in" to "Συνδεδεμένος (Cookies Ενεργά)",
            "status_logged_out" to "Μη Συνδεδεμένος (Ανώνυμη περιήγηση)",
            "visitor_id" to "Αναγνωριστικό επισκέπτη",
            "edit_manual" to "Χειροκίνητη επεξεργασία",
            "logout_btn" to "Αποσύνδεση (Εκκαθάριση Cookies)",
            "logout_confirm_title" to "Επιβεβαίωση Αποσύνδεσης",
            "logout_confirm_msg" to "Είστε βέβαιοι ότι θέλετε να αποσυνδεθείτε και να διαγράψετε όλα τα cookies;",
            "browsing_section" to "Περιήγηση & Αναζήτηση",
            "player_engine" to "Μηχανή αναπαραγωγής",
            "player_advanced" to "Για προχωρημένους (1080p/4K + Αυτόματη μετάφραση)",
            "player_classic" to "Κλασικό (Ενσωματωμένο CloudStream)",
            "pages_limit" to "Όριο σελίδων καναλιού",
            "pages_sum" to "Σελίδες που ανακτώνται κατά το άνοιγμα ενός καναλιού",
            "playlist_tag" to "Ετικέτα αναζήτησης λίστας",
            "tag_hint" to "Εισαγωγή ετικέτας (π.χ. {p})",
            "current" to "Τρέχον: ",
            "saved_msg" to "Τα δεδομένα σύνδεσης αποθηκεύτηκαν επιτυχώς",
            "cleared_msg" to "Τα δεδομένα διαγράφηκαν",
            "close" to "Κλείσιμο",
            "save" to "Αποθήκευση",
            "ok" to "Εντάξει",
            "cancel" to "Ακύρωση",
            "delete" to "Διαγραφή",
            "youtube_login" to "Σύνδεση YouTube",
            "no_data" to "Δεν βρέθηκαν δεδομένα!",
            "add_channel_btn" to "+ Προσθήκη Καναλιού / Λίστας",
            "no_channels" to "Δεν έχουν προστεθεί κανάλια ακόμα.",
            "unnamed_section" to "Ενότητα χωρίς όνομα",
            "confirm_delete_title" to "Επιβεβαίωση διαγραφής",
            "confirm_delete_msg" to "Αυτό το κανάλι θα καταργηθεί οριστικά από την αρχική σελίδα.",
            "section_name" to "Όνομα ενότητας",
            "add_new" to "Προσθήκη νέου",
            "edit_item" to "Επεξεργασία",
            "url_empty" to "Το URL δεν μπορεί να είναι κενό",
            "browse_youtube" to "Περιηγηθείτε ώστε το YouTube να μάθει τις προτιμήσεις σας",
            "url_hint" to "URL (https://...)"
        ),
        "no" to mapOf(
            "lang_title" to "Språk / Language",
            "home_section" to "Endre startside-seksjoner",
            "trending" to "Trender",
            "manage_channels" to "Administrer startsidekanaler",
            "manage_channels_sum" to "Legg til, rediger eller omorganiser egendefinerte kanaler og spillelister",
            "account_section" to "Konto og informasjonskapsler",
            "login_btn" to "Logg inn / Oppdater informasjonskapsler",
            "login_sum" to "Logg på med Google for å hente øktinformasjonskapsler",
            "status_title" to "Kontostatus",
            "status_logged_in" to "Logget inn (Cookies aktive)",
            "status_logged_out" to "Ikke logget inn (Inkognito)",
            "visitor_id" to "Besøks-ID",
            "edit_manual" to "Rediger manuelt",
            "logout_btn" to "Logg ut (Tøm informasjonskapsler)",
            "logout_confirm_title" to "Bekreft utlogging",
            "logout_confirm_msg" to "Er du sikker på at du vil logge ut og fjerne alle informasjonskapsler?",
            "browsing_section" to "Surfing og søk",
            "player_engine" to "Spillermotor",
            "player_advanced" to "Avansert (1080p/4K + auto-oversettelse)",
            "player_classic" to "Klassisk (CloudStream innebygd)",
            "pages_limit" to "Grense for kanalsider",
            "pages_sum" to "Sider hentet når du åpner en kanal",
            "playlist_tag" to "Søketag for spilleliste",
            "tag_hint" to "Skriv inn tag (f.eks. {p})",
            "current" to "Gjeldende: ",
            "saved_msg" to "Innloggingsdata lagret",
            "cleared_msg" to "Data slettet",
            "close" to "Lukk",
            "save" to "Lagre",
            "ok" to "OK",
            "cancel" to "Avbryt",
            "delete" to "Slett",
            "youtube_login" to "YouTube-innlogging",
            "no_data" to "Ingen data funnet!",
            "add_channel_btn" to "+ Legg til kanal / spilleliste",
            "no_channels" to "Ingen kanaler lagt til ennå.",
            "unnamed_section" to "Navnløs seksjon",
            "confirm_delete_title" to "Bekreft sletting",
            "confirm_delete_msg" to "Denne kanalen vil bli permanent fjernet fra startsiden.",
            "section_name" to "Seksjonsnavn",
            "add_new" to "Legg til ny",
            "edit_item" to "Rediger element",
            "url_empty" to "URL kan ikke være tom",
            "browse_youtube" to "Surf slik at YouTube kan kjenne preferansene dine",
            "url_hint" to "URL (https://...)"
        ),
        "ps" to mapOf(
            "lang_title" to "ژبه / Language",
            "home_section" to "د کور پاڼې برخې بدل کړئ",
            "trending" to "په تمایل کې",
            "manage_channels" to "د کور پاڼې چینلونه اداره کړئ",
            "manage_channels_sum" to "دودیز چینلونه او پلې لیستونه اضافه، ایډیټ یا بیا تنظیم کړئ",
            "account_section" to "حساب او کوکیز",
            "login_btn" to "ننوتل / کوکیز تازه کول",
            "login_sum" to "د سیشن کوکیز ترلاسه کولو لپاره د ګوګل سره ننوځئ",
            "status_title" to "د حساب حالت",
            "status_logged_in" to "ننوتلی (کوکیز فعال دي)",
            "status_logged_out" to "نه دی ننوتلی (پټ)",
            "visitor_id" to "د لیدونکي ID",
            "edit_manual" to "په لاسي ډول ایډیټ کول",
            "logout_btn" to "وتل (کوکیز پاکول)",
            "logout_confirm_title" to "د وتلو تایید",
            "logout_confirm_msg" to "ایا تاسو ډاډه یاست چې غواړئ ووځئ او ټول کوکیز پاک کړئ؟",
            "browsing_section" to "لټون او موندنه",
            "player_engine" to "پلیر انجن",
            "player_advanced" to "پرمختللی (1080p/4K + اتومات ژباړه)",
            "player_classic" to "کلاسیک (کلاوډ سټریم جوړ شوی)",
            "pages_limit" to "د چینل پاڼو محدودیت",
            "pages_sum" to "هغه پاڼې چې د چینل خلاصولو پر مهال ترلاسه کیږي",
            "playlist_tag" to "د پلې لیست لټون ټاګ",
            "tag_hint" to "ټاګ دننه کړئ (لکه {p})",
            "current" to "اوسنی: ",
            "saved_msg" to "د ننوتلو ډاټا په بریالیتوب سره خوندي شوه",
            "cleared_msg" to "ډاټا پاکه شوه",
            "close" to "بندول",
            "save" to "خوندي کول",
            "ok" to "سمه ده",
            "cancel" to "لغوه کول",
            "delete" to "ړنګول",
            "youtube_login" to "یوټیوب ته ننوتل",
            "no_data" to "هیڅ ډاټا ونه موندل شوه!",
            "add_channel_btn" to "+ چینل / پلې لیست اضافه کړئ",
            "no_channels" to "تر اوسه کوم چینل نه دی اضافه شوی.",
            "unnamed_section" to "بې نومه برخه",
            "confirm_delete_title" to "د ړنګولو تایید",
            "confirm_delete_msg" to "دا چینل به د تل لپاره د کور پاڼې څخه لیرې شي.",
            "section_name" to "د برخې نوم",
            "add_new" to "نوی اضافه کړئ",
            "edit_item" to "توکي ایډیټ کړئ",
            "url_empty" to "URL نشي کولی خالي وي",
            "browse_youtube" to "لټون وکړئ ترڅو یوټیوب ستاسو خوښې وپیژني",
            "url_hint" to "URL (https://...)"
        ),
        "ro" to mapOf(
            "lang_title" to "Limbă / Language",
            "home_section" to "Schimbați secțiunile paginii de pornire",
            "trending" to "În tendințe",
            "manage_channels" to "Gestionați canalele paginii de pornire",
            "manage_channels_sum" to "Adăugați, editați sau reordonați canale și playlist-uri personalizate",
            "account_section" to "Cont și Cookie-uri",
            "login_btn" to "Autentificare / Actualizare Cookie-uri",
            "login_sum" to "Conectați-vă cu Google pentru a captura cookie-urile de sesiune",
            "status_title" to "Stare Cont",
            "status_logged_in" to "Autentificat (Cookie-uri active)",
            "status_logged_out" to "Neautentificat (Incognito)",
            "visitor_id" to "ID Vizitator",
            "edit_manual" to "Editare manuală",
            "logout_btn" to "Deconectare (Ștergere Cookie-uri)",
            "logout_confirm_title" to "Confirmare deconectare",
            "logout_confirm_msg" to "Sunteți sigur că doriți să vă deconectați și să ștergeți toate cookie-urile?",
            "browsing_section" to "Navigare și Căutare",
            "player_engine" to "Motor Player",
            "player_advanced" to "Avansat (1080p/4K + Traducere automată)",
            "player_classic" to "Clasic (Integrat CloudStream)",
            "pages_limit" to "Limită pagini canal",
            "pages_sum" to "Pagini preluate la deschiderea unui canal",
            "playlist_tag" to "Etichetă căutare playlist",
            "tag_hint" to "Introduceți eticheta (ex. {p})",
            "current" to "Curent: ",
            "saved_msg" to "Datele de conectare au fost salvate cu succes",
            "cleared_msg" to "Datele au fost șterse",
            "close" to "Închide",
            "save" to "Salvează",
            "ok" to "OK",
            "cancel" to "Anulează",
            "delete" to "Șterge",
            "youtube_login" to "Autentificare YouTube",
            "no_data" to "Nu au fost găsite date!",
            "add_channel_btn" to "+ Adaugă Canal / Playlist",
            "no_channels" to "Niciun canal adăugat încă.",
            "unnamed_section" to "Secțiune fără nume",
            "confirm_delete_title" to "Confirmare ștergere",
            "confirm_delete_msg" to "Acest canal va fi eliminat definitiv de pe pagina de pornire.",
            "section_name" to "Nume secțiune",
            "add_new" to "Adaugă nou",
            "edit_item" to "Editare element",
            "url_empty" to "URL-ul nu poate fi gol",
            "browse_youtube" to "Navigați pentru ca YouTube să vă cunoască preferințele",
            "url_hint" to "URL (https://...)"
        ),
        "sv" to mapOf(
            "lang_title" to "Språk / Language",
            "home_section" to "Ändra startsidesektioner",
            "trending" to "Trender",
            "manage_channels" to "Hantera startsidekanaler",
            "manage_channels_sum" to "Lägg till, redigera eller ändra ordning på anpassade kanaler och spellistor",
            "account_section" to "Konto och cookies",
            "login_btn" to "Logga in / Uppdatera cookies",
            "login_sum" to "Logga in med Google för att hämta sessionscookies",
            "status_title" to "Kontostatus",
            "status_logged_in" to "Inloggad (Cookies aktiva)",
            "status_logged_out" to "Inte inloggad (Inkognito)",
            "visitor_id" to "Besöks-ID",
            "edit_manual" to "Redigera manuellt",
            "logout_btn" to "Logga ut (Rensa cookies)",
            "logout_confirm_title" to "Bekräfta utloggning",
            "logout_confirm_msg" to "Är du säker på att du vill logga ut och rensa alla cookies?",
            "browsing_section" to "Surfning och sökning",
            "player_engine" to "Spelarmotor",
            "player_advanced" to "Avancerad (1080p/4K + auto-översättning)",
            "player_classic" to "Klassisk (CloudStream inbyggd)",
            "pages_limit" to "Gräns för kanalsidor",
            "pages_sum" to "Sidor som hämtas när en kanal öppnas",
            "playlist_tag" to "Söktagg för spellista",
            "tag_hint" to "Ange tagg (t.ex. {p})",
            "current" to "Nuvarande: ",
            "saved_msg" to "Inloggningsdata har sparats",
            "cleared_msg" to "Data rensad",
            "close" to "Stäng",
            "save" to "Spara",
            "ok" to "OK",
            "cancel" to "Avbryt",
            "delete" to "Ta bort",
            "youtube_login" to "YouTube-inloggning",
            "no_data" to "Ingen data hittades!",
            "add_channel_btn" to "+ Lägg till kanal / spellista",
            "no_channels" to "Inga kanaler har lagts till ännu.",
            "unnamed_section" to "Namnlös sektion",
            "confirm_delete_title" to "Bekräfta radering",
            "confirm_delete_msg" to "Denna kanal kommer att tas bort permanent från startsidan.",
            "section_name" to "Sektionsnamn",
            "add_new" to "Lägg till ny",
            "edit_item" to "Redigera objekt",
            "url_empty" to "URL kan inte vara tom",
            "browse_youtube" to "Surfa så att YouTube kan lära känna dina preferenser",
            "url_hint" to "URL (https://...)"
        ),
        "uk" to mapOf(
            "lang_title" to "Мова / Language",
            "home_section" to "Змінити розділи головної сторінки",
            "trending" to "В тренді",
            "manage_channels" to "Керування каналами головної сторінки",
            "manage_channels_sum" to "Додавайте, редагуйте або змінюйте порядок каналів та списків відтворення",
            "account_section" to "Обліковий запис та cookie",
            "login_btn" to "Увійти / Оновити cookie",
            "login_sum" to "Увійдіть через Google, щоб отримати сесійні cookie",
            "status_title" to "Статус облікового запису",
            "status_logged_in" to "Вхід виконано (Cookie активні)",
            "status_logged_out" to "Вхід не виконано (Інкогніто)",
            "visitor_id" to "ID відвідувача",
            "edit_manual" to "Редагувати вручну",
            "logout_btn" to "Вийти (Очистити cookie)",
            "logout_confirm_title" to "Підтвердити вихід",
            "logout_confirm_msg" to "Ви впевнені, що хочете вийти та очистити всі файли cookie?",
            "browsing_section" to "Перегляд та пошук",
            "player_engine" to "Рушій плеєра",
            "player_advanced" to "Просунутий (1080p/4K + Автопереклад)",
            "player_classic" to "Класичний (вбудований у CloudStream)",
            "pages_limit" to "Ліміт сторінок каналу",
            "pages_sum" to "Сторінки, які завантажуються під час відкриття каналу",
            "playlist_tag" to "Тег пошуку списків",
            "tag_hint" to "Введіть тег (наприклад, {p})",
            "current" to "Поточний: ",
            "saved_msg" to "Дані для входу успішно збережено",
            "cleared_msg" to "Дані очищено",
            "close" to "Закрити",
            "save" to "Зберегти",
            "ok" to "ОК",
            "cancel" to "Скасувати",
            "delete" to "Видалити",
            "youtube_login" to "Вхід у YouTube",
            "no_data" to "Дані не знайдено!",
            "add_channel_btn" to "+ Додати канал / список",
            "no_channels" to "Канали ще не додані.",
            "unnamed_section" to "Розділ без назви",
            "confirm_delete_title" to "Підтвердити видалення",
            "confirm_delete_msg" to "Цей канал буде назавжди видалено з головної сторінки.",
            "section_name" to "Назва розділу",
            "add_new" to "Додати новий",
            "edit_item" to "Редагувати",
            "url_empty" to "URL не може бути порожнім",
            "browse_youtube" to "Переглядайте, щоб YouTube дізнався про ваші вподобання",
            "url_hint" to "URL (https://...)"
        ),
        "ur" to mapOf(
            "lang_title" to "زبان / Language",
            "home_section" to "ہوم پیج کے سیکشنز تبدیل کریں",
            "trending" to "ٹرینڈنگ",
            "manage_channels" to "ہوم پیج چینلز کا نظم کریں",
            "manage_channels_sum" to "حسب ضرورت چینلز اور پلے لسٹس شامل کریں، ترمیم کریں یا ترتیب دیں",
            "account_section" to "اکاؤنٹ اور کوکیز",
            "login_btn" to "لاگ ان / کوکیز کو اپ ڈیٹ کریں",
            "login_sum" to "سیشن کوکیز حاصل کرنے کے لیے گوگل کے ساتھ سائن ان کریں",
            "status_title" to "اکاؤنٹ کی حیثیت",
            "status_logged_in" to "لاگ ان (کوکیز فعال)",
            "status_logged_out" to "لاگ ان نہیں (انکوگنیٹو)",
            "visitor_id" to "وزیٹر آئی ڈی",
            "edit_manual" to "دستی طور پر ترمیم کریں",
            "logout_btn" to "لاگ آؤٹ (کوکیز صاف کریں)",
            "logout_confirm_title" to "لاگ آؤٹ کی تصدیق کریں",
            "logout_confirm_msg" to "کیا آپ واقعی لاگ آؤٹ کرنا اور تمام کوکیز صاف کرنا چاہتے ہیں؟",
            "browsing_section" to "براؤزنگ اور تلاش",
            "player_engine" to "پلیئر انجن",
            "player_advanced" to "ایڈوانسڈ (1080p/4K + آٹو ٹرانسلیٹ)",
            "player_classic" to "کلاسک (کلاؤڈ اسٹریم بلٹ ان)",
            "pages_limit" to "چینل کے صفحات کی حد",
            "pages_sum" to "چینل کھولتے وقت حاصل کیے گئے صفحات",
            "playlist_tag" to "پلے لسٹ سرچ ٹیگ",
            "tag_hint" to "ٹیگ درج کریں (جیسے {p})",
            "current" to "موجودہ: ",
            "saved_msg" to "لاگ ان ڈیٹا کامیابی سے محفوظ ہو گیا",
            "cleared_msg" to "ڈیٹا صاف کر دیا گیا",
            "close" to "بند کریں",
            "save" to "محفوظ کریں",
            "ok" to "ٹھیک ہے",
            "cancel" to "منسوخ کریں",
            "delete" to "حذف کریں",
            "youtube_login" to "یوٹیوب لاگ ان",
            "no_data" to "کوئی ڈیٹا نہیں ملا!",
            "add_channel_btn" to "+ چینل / پلے لسٹ شامل کریں",
            "no_channels" to "ابھی تک کوئی چینل شامل نہیں کیا گیا۔",
            "unnamed_section" to "بغیر نام کا سیکشن",
            "confirm_delete_title" to "حذف کرنے کی تصدیق کریں",
            "confirm_delete_msg" to "یہ چینل ہوم پیج سے مستقل طور پر ہٹا دیا جائے گا۔",
            "section_name" to "سیکشن کا نام",
            "add_new" to "نیا شامل کریں",
            "edit_item" to "آئٹم میں ترمیم کریں",
            "url_empty" to "URL خالی نہیں ہو سکتا",
            "browse_youtube" to "براؤز کریں تاکہ یوٹیوب آپ کی پسند جان سکے",
            "url_hint" to "URL (https://...)"
        ),
        "ku" to mapOf(
            "lang_title" to "زمان / Language",
            "home_section" to "گۆڕینی بەشەکانی پەڕەی سەرەکی",
            "trending" to "ئینجا",
            "manage_channels" to "بەڕێوەبردنی کەناڵەکانی پەڕەی سەرەکی",
            "manage_channels_sum" to "زیادکردن، دەستکاریکردن، یان ڕێکخستنەوەی کەناڵ و لیستی پەخشەکان",
            "account_section" to "هەژمار و کوکییەکان",
            "login_btn" to "چوونەژوورەوە / نوێکردنەوەی کوکییەکان",
            "login_sum" to "بۆ گرتنی کوکییەکانی دانیشتن بە گووگڵ بچۆ ژوورەوە",
            "status_title" to "دۆخی هەژمار",
            "status_logged_in" to "چووەتە ژوورەوە (کوکییەکان کاران)",
            "status_logged_out" to "نەچووەتە ژوورەوە (شاراوە)",
            "visitor_id" to "ناسنامەی سەردانکەر",
            "edit_manual" to "دەستکاریی دەستی",
            "logout_btn" to "چوونەدەرەوە (سڕینەوەی کوکییەکان)",
            "logout_confirm_title" to "دڵنیایی چوونەدەرەوە",
            "logout_confirm_msg" to "دڵنیایت دەتەوێت بچیتە دەرەوە و هەموو کوکییەکان بسڕیتەوە؟",
            "browsing_section" to "گەڕان و بینین",
            "player_engine" to "بزوێنەری پلەیەر",
            "player_advanced" to "پێشکەوتوو (1080p/4K + وەرگێڕانی خۆکار)",
            "player_classic" to "کلاسیک (ناوخۆیی CloudStream)",
            "pages_limit" to "سنووری لاپەڕەکانی کەناڵ",
            "pages_sum" to "لاپەڕەکان کە لە کاتی کردنەوەی کەناڵێکدا وەردەگیرێن",
            "playlist_tag" to "تاگی گەڕانی لیستی پەخش",
            "tag_hint" to "تاگ بنووسە (بۆ نموونە {p})",
            "current" to "ئێستا: ",
            "saved_msg" to "زانیارییەکانی چوونەژوورەوە بە سەرکەوتوویی پاشەکەوت کرا",
            "cleared_msg" to "زانیارییەکان سڕانەوە",
            "close" to "داخستن",
            "save" to "پاشەکەوت",
            "ok" to "باشە",
            "cancel" to "هەڵوەشاندنەوە",
            "delete" to "سڕینەوە",
            "youtube_login" to "چوونەژوورەوەی یوتیوب",
            "no_data" to "هیچ داتایەک نەدۆزرایەوە!",
            "add_channel_btn" to "+ زیادکردنی کەناڵ / لیستی پەخش",
            "no_channels" to "هێشتا هیچ کەناڵێک زیاد نەکراوە.",
            "unnamed_section" to "بەشی بێ ناو",
            "confirm_delete_title" to "دڵنیایی سڕینەوە",
            "confirm_delete_msg" to "ئەم کەناڵە بۆ هەمیشە لە پەڕەی سەرەکی لادەبرێت.",
            "section_name" to "ناوی بەش",
            "add_new" to "زیادکردنی نوێ",
            "edit_item" to "دەستکاریکردنی بەند",
            "url_empty" to "ناونیشان ناتوانێت بەتاڵ بێت",
            "browse_youtube" to "بگەڕێ با یوتیوب ئارەزووەکانت بزانێت",
            "url_hint" to "ناونیشان (https://...)"
        )



    )

    fun getString(sharedPref: SharedPreferences, key: String): String {
        val langCode = sharedPref.getString("youtube_language", "ar") ?: "ar"
        return translations[langCode]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}