//package com.cimanow
//
//import com.lagradost.cloudstream3.CloudStreamApp.Companion.context
//import android.os.Handler
//import android.util.Log
//import kotlin.math.min
//import com.lagradost.cloudstream3.*
//import com.lagradost.cloudstream3.LoadResponse.Companion.addTrailer
//import com.lagradost.cloudstream3.utils.*
//import org.jsoup.nodes.Element
//import android.util.Base64
//import com.lagradost.cloudstream3.utils.newExtractorLink
//import com.lagradost.cloudstream3.network.WebViewResolver
//import com.lagradost.cloudstream3.*
//import com.lagradost.cloudstream3.utils.ExtractorLink
//import com.lagradost.cloudstream3.utils.ExtractorLinkType
//import com.lagradost.cloudstream3.utils.INFER_TYPE
//import com.lagradost.cloudstream3.utils.Qualities
//import com.lagradost.cloudstream3.utils.loadExtractor
//import java.net.URLEncoder
//import kotlinx.coroutines.sync.Mutex
//import kotlinx.coroutines.sync.withLock
//import kotlin.text.toIntOrNull
//import com.lagradost.cloudstream3.newAnimeLoadResponse
//import com.lagradost.cloudstream3.newEpisode
//import com.lagradost.cloudstream3.newHomePageResponse
//import com.lagradost.cloudstream3.newMovieLoadResponse
//import com.lagradost.cloudstream3.newMovieSearchResponse
//import com.lagradost.cloudstream3.newTvSeriesLoadResponse
//import kotlinx.coroutines.Dispatchers
//import kotlinx.coroutines.withContext
//import kotlinx.coroutines.suspendCancellableCoroutine
//import kotlin.coroutines.resume
//import kotlinx.coroutines.CoroutineScope
//import kotlinx.coroutines.launch
//import android.content.Context
//import android.webkit.WebResourceRequest
//import android.webkit.WebView
//import android.webkit.WebViewClient
//import com.lagradost.cloudstream3.*
//import com.lagradost.cloudstream3.utils.*
//import com.lagradost.cloudstream3.network.CloudflareKiller
//import com.lagradost.nicehttp.requestCreator
//import com.lagradost.cloudstream3.utils.M3u8Helper
//import java.math.BigInteger
//import kotlinx.coroutines.GlobalScope
//import kotlinx.coroutines.launch
//import org.jsoup.Jsoup
//import android.annotation.SuppressLint
//import android.webkit.JavascriptInterface
//import com.lagradost.cloudstream3.utils.getQualityFromName
//import kotlinx.coroutines.withTimeoutOrNull
//import kotlinx.coroutines.CompletableDeferred
//import kotlinx.coroutines.withTimeoutOrNull
//import org.mozilla.javascript.Scriptable
//import kotlinx.coroutines.*
//import kotlinx.coroutines.withContext
//import okhttp3.OkHttpClient
//import okhttp3.Request
//
//import com.lagradost.cloudstream3.*
//import com.lagradost.cloudstream3.LoadResponse.Companion.addTrailer
//import com.lagradost.cloudstream3.utils.*
